apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: node-exporter
        image: prom/node-exporter:v1.2.2
        args:
        - --web.listen-address=:9100
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-log
          mountPath: /var/log/nginx
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
      - name: nginx-log
        hostPath:
          path: /var/log/nginx  
